### ISSUE TITLE
Plug-in doesn't do anything

### ISSUE THREAD

**Issue by jessebarnum** [sakazuki/step-functions-draw.io#44]
I added the plugin-in in draw.io, and reloaded the page, but I don't get any AWS step functions menus or options in the left sidebar.

**Comment by skroidslab** [comment]
Draw.io has now become app.diagrams.net and I believe that change is causing the plugin to break.

**Comment by sakazuki** [comment]
This plugin works fine on https://www.draw.io.
But this plugin **does not work** on https://app.diagrams.net. 
This seems to be due to the difference in security policy. 
See [this comment](https://github.com/jgraph/drawio/issues/958#issuecomment-644206032) for detail.

I comment this caution in README.md

**Comment by skroidslab** [comment]
Somehow draw.io is automatically redirecting to app.diagrams.net but if that does not happen then it does work very well. Thank you.
